name: Build + Publish
on:
  push:
    branches:
      - 'releases/**'

permissions:
  contents: write

jobs:
  check-commit-job:
    name: Check Commit
    runs-on: ubuntu-latest
    outputs:
      is_conventional: ${{ steps.checking.outputs.is_conventional }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Commit Message
        id: checking
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$COMMIT_MSG" | grep -E "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z-]+\))?: .+" > /dev/null; then
            echo "is_conventional=true" >> $GITHUB_OUTPUT
            echo "Commit follows Angular convention"
          else
            echo "is_conventional=false" >> $GITHUB_OUTPUT
            echo "Commit does not follow Angular convention, skipping workflow"
          fi

  build-job:
    name: Create Release
    needs: check-commit-job
    if: needs.check-commit-job.outputs.is_conventional =='true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          python-version: 3.12
          cache-dependency-glob: "uv.lock"

      - name: Installing Python
        run: uv pip install --python=3.12 pip

      - name: Clear cache
        run: uv cache clean

      - name: Run Tests
        id: testing
        run: |
          uv run pytest
          echo "::testing name=pytest_result::true"

      - name: Build Project
        if: steps.testing.outcome == 'success'
        run: uv build

      - name: Bump Version
        id: tagging
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: workwork

      - name: Release Version
        if:  ${{steps.tagging.outputs.new_tag != 'undefined'  && steps.tagging.outputs.new_tag != ''}}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tagging.outputs.new_tag }}
          name: ${{ steps.tagging.outputs.new_tag }}
          body: ${{ steps.tagging.outputs.changelog }}
