
name: Build and Publish

on:
  push:
    branches:
      - main
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: 3.12
            
      - name: Run Tests
        run: uv run pytest tests
